### ISSUE TITLE
Flushing most events

### ISSUE THREAD

**Issue by nevir** [davodesign84/react-native-mixpanel#10]
I'm curious why you're explicitly flushing on most calls? Seems like that's going to consume a fair bit of bandwidth for common uses

**Comment by JAStanton** [comment]
I second this. HTTP request for every `track` and `trackWithProperties` is a lot. 
https://github.com/mixpanel/mixpanel-iphone/blob/84f116804a48312f397f5ae09abea76d3cf5083f/Mixpanel/Mixpanel.h#L570

mixpanel docs say it'll flush every minute by default.

or you can init with `flushInterval` to override (0 is never):
`https://github.com/mixpanel/mixpanel-iphone/blob/84f116804a48312f397f5ae09abea76d3cf5083f/Mixpanel/Mixpanel.h#L322`

They also use app lifecycle to flush as well, when it enters the background it'll flush then too which is probably just enough on its own regardless of the minute timer.

**Comment by davodesign84** [comment]
The reason behind this is that not knowing the type of project this library will be used in, I'd prefer to be on the safe side. Most apps fail to get an average session time of 1 minute anyway.

What would be nice would be to create a separate call for flushing, or flushing when the app goes in background.
PR anybody? :)

**Comment by JAStanton** [comment]
It should already be flushing when you go in the background. That's what
mix panel does by default, on my mobile but I thought I already linked to
that? Maybe not

**Comment by nevir** [comment]
> What would be nice would be to create a separate call for flushing, or flushing when the app goes in background.

Mixpanel's library [does this already](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1213-L1215)
