### ISSUE TITLE
Support get distinct id

### ISSUE THREAD

**Issue by sslash** [davodesign84/react-native-mixpanel#11]
It would be nice to support getting the Mixpanel function "get distinct id". For instance if you want to store the identity in a database to reuse it on the web for the same user

**Comment by davodesign84** [comment]
Thanks @sslash I'll have a look if I can find the time to expose that.

**Comment by mikelambert** [comment]
@sslash "get distinct id" is supported in the web API, but not in the iOS API, right?
https://mixpanel.com/site_media/doctyl/uploads/iPhone-spec/Classes/Mixpanel/index.html#//apple_ref/occ/cl/Mixpanel

So probably would be better to ask the Mixpanel iOS team to expose it in their API first, before react-native can even expose it? Or am I misunderstanding what function you want exposed?

**Comment by davodesign84** [comment]
@mikelambert thanks, I had forgotten to reply to this after checking it.
I could try to ask them and see how it goes.

**Comment by ewdicus** [comment]
Just a heads up, this isn't a function. It's exposed as a property for iOS: https://mixpanel.com/site_media/doctyl/uploads/iPhone-spec/Classes/Mixpanel/index.html#//apple_ref/occ/instp/Mixpanel/distinctId

**Comment by ewdicus** [comment]
I went ahead and added a pull request: https://github.com/davodesign84/react-native-mixpanel/pull/25

There might be a better way to expose this as a property.

**Comment by davodesign84** [comment]
That's great, but would be nice to get the same on Android. Anyone able to submit a PR for Android?

**Comment by kevando** [comment]
Is this the issue where device ID does not persist? [Link](https://github.com/rebeccahughes/react-native-device-info/pull/58)

Whenever I change simulators or update the app, the user in Mixpanel changes. How can I prevent that from happening?

**Comment by aakashsigdel** [comment]
@kevando I think you can do that with alias and identify

Closing this thread as getDistinctId is already implemented on both iOS and android
