### ISSUE TITLE
Library not found for -lRNMixpanel-tvOS

### ISSUE THREAD

**Issue by austin-sprawls** [davodesign84/react-native-mixpanel#112]
I'm using RN version 0.37. After installing the Mixpanel Pod and linking react-native-mixpanel, I'm getting this build error: 
library not found for -lRNMixpanel-tvOS

Any suggestions to solve this?

**Comment by peteroid** [comment]
If your app has nothing to do with tvOS, just remove that linked library in the section of "Link binary ..." in XCode

ref: https://github.com/oblador/react-native-vector-icons/issues/461

**Comment by austin-sprawls** [comment]
Thanks, that worked.
