### ISSUE TITLE
No iOS folder to setup with newer React-Native

### ISSUE THREAD

**Issue by julesmoretti** [davodesign84/react-native-mixpanel#115]
Hello there:

I am trying to follow the instructions to set this up, but in the latest version of react-native there is no apparent ios folder to integrate the cocoapod configuration you mentioned.

Do you have any suggestions on how I could bypass that step?

```
├── expo@21.0.2
├── firebase@4.6.0
├── jest-expo@21.0.2
├── react@16.0.0-alpha.12
├── react-native@0.48.4
├── react-native-keyboard-responsive-view@0.1.7
├── react-native-mixpanel@0.0.16
├── react-native-scripts@1.5.0
├── react-native-slider@0.11.0
├── react-navigation@1.0.0-beta.13
├── react-redux@5.0.6
├── react-test-renderer@16.0.0-alpha.12
└── redux@3.7.2
```

```
react-native-cli: 2.0.1
react-native: 0.48.4
```

`npm version: 4.6.1`

Thank you for your help

**Comment by sesm** [comment]
Did you use `create-react-native-app` to create your app? If yes, then you need to 'eject': https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#ejecting-from-create-react-native-app
