### ISSUE TITLE
ld: framework not found Mixpanel

### ISSUE THREAD

**Issue by AlmogRnD** [davodesign84/react-native-mixpanel#127]
I'm getting the following error on iOS when I try to build/compile my app. I have mixpanel installed and using pods which shows that it was installed. I also ran react-native link 

ld: framework not found Mixpanel
clang: error: linker command failed with exit code 1 (use -v to see invocation)

 "react-native": "^0.53.3",
 "react-native-mixpanel": "0.0.16",
Node v9.6.1
NVM latest

**Comment by tnsengimana** [comment]
@AlmogRnD have you tried the solution on issue https://github.com/davodesign84/react-native-mixpanel/issues/42? I was having similar problem and it worked for me.

**Comment by migcv** [comment]
I had the same issue and fixed it by adding in the XCode project Pods.xcodeproj into the folder Frameworks

Right click on Frameworks and click -> add Files to "project_name". Then go to the folder Pods and add Pods.xcodeproj.
