### ISSUE TITLE
Handling notifications hook

### ISSUE THREAD

**Issue by imdadahad** [davodesign84/react-native-mixpanel#139]
Is there code in this library to listen for notifications coming from mixpanel and then subsequently read any custom data passed through?
Similar to the onesignal react native library where you can setup listeners for when a notification is received, opened etc.

**Comment by Tejas-narola** [comment]
Hey How to solved this? please give me some suggestion.

**Comment by bruscantini** [comment]
lol me too @imdadahad ! Did you figure it out? Notifications from FCM work, but not those initiated by Mixpanel...
