### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by alizbazar** [davodesign84/react-native-mixpanel#14]
I'm getting the same error as in #6 . Tried setting the Other Linker Flags with no results. Any tips?

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Mixpanel", referenced from:
      objc-class-ref in libRNMixpanel.a(RNMixpanel.o)```

![Error message in XCode](https://cloud.githubusercontent.com/assets/6986811/11878493/7d80d2ac-a4f6-11e5-8fd4-15441696a9d8.png)

**Comment by davodesign84** [comment]
Do you have a sample project to reproduce this?

**Comment by alizbazar** [comment]
Sorry, I forgot to include the Mispanel SDK - thought it was included.

**Comment by davodesign84** [comment]
No worries, it can happen :octocat:

**Comment by arunshan** [comment]
Hi Guys, I did follow the exact instructions to install the Mixpanel SDK but I still get this error. 

I also see the following when I do `pod install`
```
[!] The `foodhogmobile [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `foodhogmobile [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by Knotschi** [comment]
I had the same issue. This fixed it for me: http://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods/26077106#26077106

**Comment by florinlazau** [comment]
I have the previews issue and I have used [this](https://github.com/davodesign84/react-native-mixpanel) installation steps.
Any help would be appreciated!

**Comment by DataGreed** [comment]
I still have this problem. Cannot get this to work.
