### ISSUE TITLE
People Analytics (Mixpanel.set) - NOT WORKING !!

### ISSUE THREAD

**Issue by sujay-bidchat** [davodesign84/react-native-mixpanel#143]
react-native: 0.47.1
react-native-mixpanel: 0.0.16

@davodesign84 I am trying to set up People Analytics.
So I tried the following code :-
```
Mixpanel.identify(authModel.email);
Mixpanel.set({ $email: email, id: id });
```
But Mixpanel is not getting that data.
Response from Mixpanel :-

> WE DON'T HAVE ANY DATA!
> You haven't sent us any user profiles yet. Don't worry: it's easy to get set up

When I click Check button (Once you set a property, check to make sure we're receiving data) response I get :-
> We have not received any data yet.

**Comment by shredder-rull** [comment]
@sujay-bidchat try to change order:
`
Mixpanel.set({ $email: email, id: id });
Mixpanel.identify(authModel.email);
`

**Comment by sujay-bidchat** [comment]
@shredder-rull Still not working for me 👎

**Comment by sabbyt54** [comment]
Did you manage to resolve @sujay-bidchat ?

**Comment by sujay-bidchat** [comment]
@sabbyt54 I was not able to resolve that issue. @shredder-rull  Please check.

**Comment by sidhusubhash** [comment]
it's working for me...

Mixpanel.identify(`${unique_id}`)
              Mixpanel.set({
                "$email": `${person.email}`,
              });

try this....

**Comment by amoljain** [comment]
For me identify seems to work well on iOS but not on Android :/

Any solutions?

**Comment by andycloke** [comment]
same issue here. working on ios but not on android. `"react-native-mixpanel": "1.1.1",` `"react-native": "0.57.0",`

**Comment by kyleclegg** [comment]
Several people (including me) have observed that calling `Mixpanel.set({ // the data })` a second time results in data flowing into Mixpanel properly for Android.

https://github.com/davodesign84/react-native-mixpanel/issues/196#issuecomment-552695203
