### ISSUE TITLE
Undefined is not an object (evaluating '_reactNativeMixpanel.Mixpanel.sharedInstanceWithToken')

### ISSUE THREAD

**Issue by jorge-sanz** [davodesign84/react-native-mixpanel#148]
I am getting this error with this code:
```
import { Mixpanel } from 'react-native-mixpanel';
...
Mixpanel.sharedInstanceWithToken(TOKEN);
Mixpanel.track("New order");
```

Any idea of how to solve it? Thank you so much! 🙂

**Comment by syafiq90** [comment]
Mixpanel.default.sharedInstanceWithToken(TOKEN);

All must be Mixpanel.default

**Comment by syafiq90** [comment]
please Fix this issue or update your Document @davodesign84

**Comment by jorge-sanz** [comment]
@syafiq90 it's working right now for me. Not sure how I fixed it. I restarted the project again.

**Comment by SMJ93** [comment]
hey guys, we are getting the same issue:

`Mixpanel.sharedInstanceWithToken("APIxxxxxx")` 

Error: `TypeError: Cannot read property 'sharedInstanceWithToken' of undefined.

Versions:

- react-native-mixpanel: 1.1.1
- pod 'Mixpanel', '~> 3.3.3'
- react-native: 0.55.3

When console logging `Mixpanel` the functions show up as expected:

![screen shot 2018-10-01 at 13 39 41](https://user-images.githubusercontent.com/2145641/46288984-8785a000-c57f-11e8-966b-976b4ff8616e.png)

Let me know if you need any more info!

Cheers

**Comment by SMJ93** [comment]
It looks like `RNMixpanel` is `undefined` in `node_modules/react-native-mixpanel/index.js` line 4:

const { RNMixpanel } = NativeModules

**Comment by SMJ93** [comment]
I forgot to link it in xcode 🤦‍♂️:

Go to node_modules ➜ react-native-mixpanel and add RNMixpanel.xcodeproj
In XCode, in the project navigator, select your project. Add libRNMixpanel.a to your project's Build Phases ➜ Link Binary With Libraries

**Comment by paalex** [comment]
`import Mixpanel from 'react-native-mixpanel'` instead of `var Mixpanel = require('react-native-mixpanel')` did it for me.
The module now exports a `default` object and a `MixpanelInstance` object. Therefore, the above default import should be used or `import {MixpanelInstance} from 'react-native-mixpanel'` for the new (?) interface

**Comment by fachrinfl** [comment]
you can use like this, i found in file index.js:
```
const mixpanel = new MixpanelInstance(TOKEN)
await mixpanel.initialize()
mixpanel.track('my event')
```

**Comment by nikodunk** [comment]
My issue was not in the Javascript, but in this:

https://github.com/davodesign84/react-native-mixpanel/issues/50#issuecomment-258065688

**Comment by SiddharthRana** [comment]
Try to import with braces like : 

import Mixpanel from 'react-native-mixpanel';
