### ISSUE TITLE
Use of undeclared identifier 'Mixpanel' -- build errors on iOS

### ISSUE THREAD

**Issue by SunburtReynolds** [davodesign84/react-native-mixpanel#151]
Unfortunately, the most recent release (1.1.0) appears to be broken on iOS.

I tried to integrate the library following both the automatic and manual steps defined [here](https://github.com/davodesign84/react-native-mixpanel#installation). After that failed, I reintegrated React Native and all dependencies purely through CocoaPods as described [here](http://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies). My built fine in both cases _before_ adding `react-native-mixpanel`. However, after adding your library, I received errors from Xcode. See screen shot below.

<img width="854" alt="screen shot 2018-08-16 at 10 48 57 am" src="https://user-images.githubusercontent.com/6595948/44219754-72c18a00-a142-11e8-8bd8-190a9de2d2c1.png">

Here are the offending lines:
https://github.com/davodesign84/react-native-mixpanel/blob/master/RNMixpanel/RNMixpanel.m#L54
https://github.com/davodesign84/react-native-mixpanel/blob/master/RNMixpanel/RNMixpanel.m#L60

While building, Xcode does not recognize `mixpanel`. It looks like @andrejunges authored the PR, so maybe he has a few suggestions.

Thanks for your hard work!

**Comment by Gadigg** [comment]
@andrejunges Do you have merge permissions on this repo? 
There's a PR to fix this waiting to get merged... 

https://github.com/davodesign84/react-native-mixpanel/pull/149

**Comment by andrejunges** [comment]
@Gadigg Unfortunately I don't have permissions.
