### ISSUE TITLE
Can't build for staging environment on iOS

### ISSUE THREAD

**Issue by matt33** [davodesign84/react-native-mixpanel#157]
If I try to build for other than Debug or Release I am getting this error:

```
- directory not found for option '-Lapp-name/ios/build/Staging-iphoneos/Mixpanel'
- library not found for -lPods-AppName
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have tried adding `$(PROJECT_DIR)/build/Debug-iphoneos/Mixpanel` into Library Search Paths but the same error appears. Which is weird cause the previous dir works for debug and for release build.

Any ideas on how to fix this? What to set properly?

react-native: 0.52.2
react-native-mixpanel: 1.1.1

**Comment by rscoones** [comment]
https://github.com/Microsoft/react-native-code-push/issues/893#issuecomment-317648454
This comment helped me.
When installing cocoapods, the workspace did not create the build folders properly for custom schemes (non debug/release)

**Comment by matt33** [comment]
This helped, thank a lot!
