### ISSUE TITLE
Doesn't work unless also initialized in objc

### ISSUE THREAD

**Issue by joshblour** [davodesign84/react-native-mixpanel#16]
Following the instructions, I wasn't able to track events or identify users until I called `[Mixpanel sharedInstanceWithToken:MIXPANEL_TOKEN];` from objc. I didn't get any errors...I just didn't see any of the events in my mixpanel dashboard.

(I needed to call `sharedInstanceWithToken` in JS _and_ in objc)

Note: mixpanel library was installed manually, not from cocoapods.

**Comment by davodesign84** [comment]
I haven't tested thoroughly  with a manual installation of Mixpanel. Have you tried with cocoapods to see if the same issue occurs?

**Comment by mikelambert** [comment]
Yes, Cocoapods has this bug too. Android works, but iOS did not. Basically, events are not being automatically flushed on iPhone, though calling flush() manually does work.

The reason for this is that initWithToken sets up a bunch of listeners, including applicationDidBecomeActive, which is what sets up the FlushTimer. Unfortunately, when Mixpanel initialized in React Native JS, it's too late for addListener to catch applicationDidBecomeActive, and so iPhone events never get flushed. :( Even sticking the initialization in index.ios.js is not sufficient here.

From what I can tell, our two options are either a small hack to call the private method Mixpanel.applicationDidBecomeActive, or to document that iOS needs early-initialization in ObjC/Swift code.
