### ISSUE TITLE
Android Module track no People in mixpanel panel

### ISSUE THREAD

**Issue by mactive** [davodesign84/react-native-mixpanel#17]
I track the data use Charles with SSL 
found that iOS do post data to @/engage/
so mixpanel will create a person for you

[code@mixpaneliPhoneSDK ](https://github.com/mixpanel/mixpanel-iphone/blob/772085d2b8c7b1a4ae949184c867325ecf62c4f1/Mixpanel/Mixpanel.m#L658)

But Android did not post the data.

**Comment by origsun** [comment]
I created a pull request to fix this.

https://github.com/davodesign84/react-native-mixpanel/pull/18

**Comment by davodesign84** [comment]
Thank you! Merged.
