### ISSUE TITLE
Do you plan to  still support this repo?

### ISSUE THREAD

**Issue by lorenc-tomasz** [davodesign84/react-native-mixpanel#171]
As above, @davodesign84 do plan to support this repo?

**Comment by lorenc-tomasz** [comment]
Maybe consider moving the repo into  React Native Community  https://github.com/react-native-community ?

**Comment by lorenc-tomasz** [comment]
@davodesign84 ?

**Comment by apamphilon** [comment]
@lorenc-tomasz, it's not looking good :-(

**Comment by davodesign84** [comment]
@lorenc-tomasz It was mentioned a few times in the past, I do not have time to support this package, but I'll happily merge PRs and welcome any volunteering contributor :)

Once Mixpanel releases their React-Native SDK will most likely be deprecated though.

**Comment by lorenc-tomasz** [comment]
@davodesign84 Any info about official mixpanel SDK?

**Comment by MaxiSantos** [comment]
@lorenc-tomasz they are currently working on the react-native sdk
[https://community.mixpanel.com/questions/856/feature-suggestion-react-native-sdk.html](https://community.mixpanel.com/questions/856/feature-suggestion-react-native-sdk.html)
