### ISSUE TITLE
Mixpanel 5.6.0

### ISSUE THREAD

**Issue by ChrisEdson** [davodesign84/react-native-mixpanel#174]
Is there any chance we could update to the latest Mixpanel Android (5.6.0) - so that we can get FCM support?

**Comment by apamphilon** [comment]
Will this be as simple as updating the library in the build.gradle file or will there be more to it?

**Comment by lorenc-tomasz** [comment]
They moved to FCM.

**Comment by apamphilon** [comment]
I have followed the guide here: 

https://help.mixpanel.com/hc/en-us/articles/115004706906-Google-Cloud-Messaging-GCM-Or-Firebase-Cloud-Messaging-FCM

They mention to  `'update your Mixpanel library to v5.5 and above'`.

I have updated the `node_modules/react-native-mixpanel/android/build.gradle` file to the below:

```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile "com.mixpanel.android:mixpanel-android:5.6.0"
}
```

Does anyone know if this will be sufficient or if further chages will be needed?

**Comment by lorenc-tomasz** [comment]
It will be. I have done it by my self. Maybe I will create PR but don't know if it has any sense as this repo is probably abandon by author.

**Comment by apamphilon** [comment]
@lorenc-tomasz I was thinking the exact same thing. If there is enough demand for this plugin it might be worth seeing if anyone is interested in taking it over.

**Comment by lorenc-tomasz** [comment]
Agree. I was thinking about it, but sadly if I get more projects I will not have time to support the module. My suggestion was to move the repo to react community but without response.

**Comment by lorenc-tomasz** [comment]
Have added support for 5.6.0 with link how to migrate to FCM: https://github.com/lorenc-tomasz/react-native-mixpanel/tree/fcm

**Comment by lorenc-tomasz** [comment]
I have created the PR here but I don't believe that somone will merge it.

**Comment by kyleclegg** [comment]
The upgrade to Mixpanel Android 5.6 has been merged.
