### ISSUE TITLE
Apple Rejection - TMS-90338: Non-public API usage (WKInterfaceDevice)

### ISSUE THREAD

**Issue by evaldsurtans** [davodesign84/react-native-mixpanel#184]
Please update mixpanel-iphone dependency, it is not usable now with iOS.
https://github.com/mixpanel/mixpanel-iphone/issues/850

**Comment by evaldsurtans** [comment]
Nevermind, need to run in ./ios 
`carthage update`

**Comment by zihejia** [comment]
hi @evaldsurtans , have you solved the issue by updating Mixpanel?

**Comment by evaldsurtans** [comment]
Uninstall and reinstall module + dependencies. Problem has been solved
within mixpanel iphone sdk in their github repo
