### ISSUE TITLE
Mixpanel People Set should allow non-string values

### ISSUE THREAD

**Issue by ewdicus** [davodesign84/react-native-mixpanel#21]
Hello,

This just tripped me up - It looks like the mixpanel function allows non string types:
https://mixpanel.com/site_media/doctyl/uploads/iPhone-spec/Classes/MixpanelPeople/index.html#//apple_ref/occ/instm/MixpanelPeople/set:

But here it's limiting to string: https://github.com/davodesign84/react-native-mixpanel/blob/master/RNMixpanel/RNMixpanel.m#L75

Any reason why `set` doesn't take an NSDictionary instead of key, value?

Thanks,
Elliott

**Comment by ewdicus** [comment]
Added a pull request: https://github.com/davodesign84/react-native-mixpanel/pull/22

**Comment by davodesign84** [comment]
Merged :)
