### ISSUE TITLE
Error installing mixpanel

### ISSUE THREAD

**Issue by arunshan** [davodesign84/react-native-mixpanel#23]
I get the following error when I added mixpanel to my existing project. I installed the SDK and linked the appropriate files as documented.

```
Undefined symbols for architecture x86_64:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in libMixpanel.a(MPWebSocket.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by arunshan** [comment]
Solved it had to add `-licucore` to Other Linker Flags in the main Xcode Project Build Settings

**Comment by faceyspacey** [comment]
I'm having the same issue. I added `-licucore`, but it didn't fix it. Was there anything else you had to do?

**Comment by arunshan** [comment]
@faceyspacey are you seeing the same error after adding `-licucore` ?

**Comment by faceyspacey** [comment]
I was, i had to manually add `libMixPanel.a`. Not sure it wasn't added by the coca pod build phase. But the combination of the two made it work.

**Comment by kevando** [comment]
Holy shit this worked.

**Comment by kevando** [comment]
Can we please update the installation instructions to include this?

**Comment by rajatgupta1993** [comment]
@faceyspacey  where did u add `libMixPanel .a` from ? 
I am getting this same issue , and i am not using cocoapods for installing the sdk . 
@arunshan  please help .

**Comment by nicotroia** [comment]
Anyone having this issue, try installing mixpanel via podfile

`sudo gem install -n /usr/local/bin cocoapods` 
`cd ./ios`
`pod init`
Open the "Podfile" and add the line `pod 'Mixpanel'` inside the main target
`pod install`
then probably `react-native link` again

This solved any missing dependencies, architecture issues and mach-o linker errors that I was having trying to install this package.
