### ISSUE TITLE
Has anyone managed to get iOS push notifications working with @react-native-firebase/messaging 6.7.1?

### ISSUE THREAD

**Issue by SMJ93** [davodesign84/react-native-mixpanel#234]
It used to work fine with firebase v5, but since upgrading I don't receive any notifications.

Here is my code:

JS:
```
    const pushToken = await messaging().getToken();
    Mixpanel.addPushDeviceToken(pushToken);
    Mixpanel.identify(userId);
```

AppDelegate.m

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  Mixpanel *mixpanel = [Mixpanel sharedInstance];
  [mixpanel.people addPushDeviceToken:deviceToken];
}
```

**Comment by 0hio-creator** [comment]
Hey,
 
I'm using the following to register the token with mixpanel.

for ios 

```
let token = await messaging().getAPNSToken()
            Mixpanel.addPushDeviceToken(token)
```


Not using any native code 
- request permissions
```
 const authStatus = await messaging().requestPermission();
```

Using firebase messaging to handle responese
```
export const backgroundHandler = async () => {
    messaging().setBackgroundMessageHandler(async remoteMessage => {
        console.log('Message handled in the background!', remoteMessage);
    });
} 
```

**Comment by SMJ93** [comment]
Hi @0hio-creator, what about calling `addPushDeviceToken` in the AppDelegate.m?

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  Mixpanel *mixpanel = [Mixpanel sharedInstance];
  [mixpanel.people addPushDeviceToken:deviceToken];
}
```

Don't you need to do this?

**Comment by 0hio-creator** [comment]
@SMJ93 
`Mixpanel.addPushDeviceToken(token)` does the same thing but slightly different usage.

The delegate sets a callback to send the apns token whenever didRegisterForRemoteNotificationsWithDeviceToken is called.

Where as `Mixpanel.addPushDeviceToken(token)` is called where you choose to run it.

`messaging().requestPermission()` Is the firebase call for registering for remote notifications. So i did ~something like this

```
var authStatus = await messaging().requestPermission()
// check user has given permission
if (authStatus == 1 || authStatus ==2) {
      let token = await messaging().getAPNSToken()
      Mixpanel.addPushDeviceToken(token)
}
```
After i register for notifications. 

Another thing to note is that you need to have called `Mixpanel.identify` somewhere before either Mixpanel.addPushDeviceToken or the delegate.m code is called.
Particularly watch for the case of an app reinstall

**Comment by SMJ93** [comment]
Thanks @0hio-creator !

**Comment by roni-castro** [comment]
Have anyone had problem on receiving mixpanel push notification on Foreground (app is visible to the user)? Currently I am not able to receive it on foreground, but I receive it on background.
