### ISSUE TITLE
Pod install fails on v1.1.14

### ISSUE THREAD

**Issue by jacquesdev** [davodesign84/react-native-mixpanel#235]
I get this error when trying to do pod install. Looks like branch/tag 3.6.2 was deleted from the main repo.

![Screenshot 2020-05-27 at 13 03 35](https://user-images.githubusercontent.com/7842197/83017123-0401a800-a01b-11ea-983e-7b7011843138.png)

**Comment by altany** [comment]
@jacquesdev Have you tried upgrading to `1.2.0`? That seems to fix it for me.

**Comment by jacquesdev** [comment]
That seems to have done the trick, thank you!
