### ISSUE TITLE
Has Anyone Successfully had android push notifications working?

### ISSUE THREAD

**Issue by bpfeiffer187** [davodesign84/react-native-mixpanel#236]
has anyone been successful with getting android notifications going? I followed steps in the repo and doesn't work for me. 

If you did get it working would you mind assisting me?

**Comment by MoeMamdouh** [comment]
how did you fix it?

**Comment by MoeMamdouh** [comment]
> has anyone been successful with getting android notifications going? I followed steps in the repo and doesn't work for me.
> 
> If you did get it working would you mind assisting me?

how did you fix it?
