### ISSUE TITLE
Events not being fired to Mixpanel

### ISSUE THREAD

**Issue by arunshan** [davodesign84/react-native-mixpanel#24]
@davodesign84
I am using the following snipped to trigger check_in event to mixpanel. I am unable to see the event in Live View on Mixpanel Dashboard.

```
const Mixpanel = require('react-native-mixpanel')
Mixpanel.sharedInstanceWithToken(config.mixpanel.token)

Mixpanel.trackWithProperties('check_in', {
        type: type,
        user_id: user.id.toString(),
        status: 'success',
        table_id: table_id.toString(),
        restaurant_id: restaurant_id.toString(),
        admin_user_id: admin_user_id.toString(),
        waiter_user_id: waiter_user_id.toString(),
        event_timestamp: (new Date().getTime()).toString()
      })
```

**Comment by davodesign84** [comment]
Hi @arunshan ,

this is probably related to this issue https://github.com/davodesign84/react-native-mixpanel/issues/16.

Try initialise in Obj-c or update to 0.0.8 and let me know.

**Comment by arunshan** [comment]
@davodesign84 Thank you. That worked!

**Comment by rajatgupta1993** [comment]
@arunshan  @davodesign84  hey guys, 
I am also facing the same issue, I am using 0.0.10 
I have done 
   `const Mixpanel = require('react-native-mixpanel')
     Mixpanel.sharedInstanceWithToken(config.mixpanel.token)`

and in the on click function I have done this 
    `Mixpanel.track("Like Pressed");`

in my appdelegate.m 
`#import "Mixpanel.h"    
  #define MIXPANEL_TOKEN @"3e34db956ef278d1dfdfed994fa91808"   
    [Mixpanel sharedInstanceWithToken:MIXPANEL_TOKEN];`
but there is no event in the mixpanel dashboard . 

what should i do ? what do you mean by "Try initialise in Obj-c" ?

**Comment by luisfuertes** [comment]
I have this issue (Android and ios)

My App.js
```
import Mixpanel from 'react-native-mixpanel'
Mixpanel.sharedInstanceWithToken(MIXPANEL_TOKEN)

class App extends Component {
}
```

When user register:
```
      Mixpanel.createAlias(userId)
      Mixpanel.setOnce({ $email: email, Created: new Date().toISOString() })
```

When load auth data:
```
    Mixpanel.identify(userId)
    Mixpanel.track('event test')
```

Anybody return error, but in Mixpanel panel i cant see anything.
