### ISSUE TITLE
Events not being fired to Mixpanel

### ISSUE THREAD

**Issue by luisfuertes** [davodesign84/react-native-mixpanel#250]
I have mixpanel configured without errors, but cant see my events or my users in Mixpanel dashboard.

To install i only write: `yarn add react-native-mixpanel` and `npx react-native run-android`

My versions:
```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-mixpanel": "^1.2.0",
```

My App.js
```
import Mixpanel from 'react-native-mixpanel'
Mixpanel.sharedInstanceWithToken(MIXPANEL_TOKEN)

class App extends Component {
}
```

When user register:
```
      Mixpanel.createAlias(userId)
      Mixpanel.setOnce({ $email: email, Created: new Date().toISOString() })
```

When load auth data:
```
    Mixpanel.identify(userId)
    Mixpanel.track('event test')
```

Anybody return error, but in Mixpanel panel i cant see anything.

And is token, true? Not api key. To init app.
<img width="211" alt="Captura de pantalla 2020-08-03 a las 15 01 01" src="https://user-images.githubusercontent.com/18212615/89185283-4820a400-d59a-11ea-838e-7a11b56adffc.png">

And in live preview:
<img width="1486" alt="Captura de pantalla 2020-08-03 a las 15 02 58" src="https://user-images.githubusercontent.com/18212615/89185408-7a320600-d59a-11ea-8af4-f61fdc5cb014.png">

It should show my "track" events in "Live view data" in dashborad, is correct? I cant see my data

**Comment by luisfuertes** [comment]
Ok in server side it solved adding api_host: 
```
mixpanel.init("YOUR_TOKEN", { "api_host": "https://api-eu.mixpanel.com" }, "");
```

But how can i set api_host with react-native-mixpanel?

**Comment by luisfuertes** [comment]
Ok, in android i had to add this to the manifest
```
<meta-data android:name="com.mixpanel.android.MPConfig.EventsEndpoint"
           android:value="https://api-eu.mixpanel.com/track" />
<meta-data android:name="com.mixpanel.android.MPConfig.PeopleEndpoint"
           android:value="https://api-eu.mixpanel.com/engage" />
<meta-data android:name="com.mixpanel.android.MPConfig.GroupsEndpoint"
           android:value="https://api-eu.mixpanel.com/groups" />
```

And on iOS y try to send url with launchOptions but it doesnt work.
```
Mixpanel.sharedInstanceWithToken(MIXPANEL_TOKEN, false, false, false, { serverURL: 'https://api-eu.mixpanel.com' })

```

Any idea how can it fix it on iOS? Doc say this:
```
self.mixpanel = [Mixpanel sharedInstanceWithToken:@"MIXPANEL_TOKEN" launchOptions:launchOptions];
self.mixpanel.serverURL = @"https://api-eu.mixpanel.com";
```

But i dont know how can i add that

**Comment by tibbus** [comment]
I tried your fix for Android, but it is still not working for me.

**Comment by luisfuertes** [comment]
@tibbus Your mixpanel server url is in EU?

**Comment by tibbus** [comment]
Yes, I got from the panel: https://api-eu.mixpanel.com

**Comment by luisfuertes** [comment]
meta-data are inside <application> in mannifest?
```

    <application
      android:name=".MainApplication"
      ...
      android:theme="@style/AppTheme">

      <meta-data android:name="com.mixpanel.android.MPConfig.EventsEndpoint"
                android:value="https://api-eu.mixpanel.com/track" />
      <meta-data android:name="com.mixpanel.android.MPConfig.PeopleEndpoint"
                android:value="https://api-eu.mixpanel.com/engage" />
      <meta-data android:name="com.mixpanel.android.MPConfig.GroupsEndpoint"
                android:value="https://api-eu.mixpanel.com/groups" />
```

**Comment by luisfuertes** [comment]
For ios maybe if add:
```

**Comment by luisfuertes** [comment]
Another solution (more permanent, since you don't have to add every time you do an npm install) is to create an instance in our AppDelegate.m.

First add the import (before `#if DEBUG`): `#import "Mixpanel / Mixpanel.h"`

and in didFinishLaunchingWithOptions:
```
  Mixpanel *mixpanel = [Mixpanel sharedInstanceWithToken:@"MIXPANEL_TOKEN"];
  mixpanel.serverURL = @"https://api-eu.mixpanel.com";
```

**Comment by Rabursky** [comment]
I have a raised a small quickfix.
Once/if this is merged README could be updated to surface this functionality.
https://github.com/davodesign84/react-native-mixpanel/pull/253

**Comment by davodesign84** [comment]
Merged!

**Comment by luisfuertes** [comment]
great thx
