### ISSUE TITLE
MIX_PANEL.showInAppMessageIfAvailable() throws "Unhandled promise rejection", ReferenceError : Can't find variable: token

### ISSUE THREAD

**Issue by DipanshKhandelwal** [davodesign84/react-native-mixpanel#256]
`MIX_PANEL.showInAppMessageIfAvailable();`

Every time I try to call this function, I face the following error.

`Throws same error for Android and iOS`

**Error** : `"Unhandled promise rejection", ReferenceError : Can't find variable: token`

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-07 at 10 00 39](https://user-images.githubusercontent.com/24923974/92348599-2a8eaf00-f0f1-11ea-9e97-33e0353ab858.png)

**Comment by IevgenRagulin** [comment]
Would be awesome to have this merged. Right now `showInAppMessageIfAvailable` is unusable really:(

**Comment by DipanshKhandelwal** [comment]
I understand. It was a problem for my team as the `inAppMessage` was popping up at the time when things were still initialising, using a fork for now. Would be great to get it directly from the main repository.
Thanks.

**Comment by IevgenRagulin** [comment]
Do you have permissions to merge this? Or could @davodesign84 merge this please?

**Comment by davodesign84** [comment]
Done :) unfortunately I don't participate work anymore on react native and don't have the time to follow updates and such but a nice mention and at least a couple of people test it I'm happy to merge :)

**Comment by IevgenRagulin** [comment]
Thank you @davodesign84 ! Would you be able to also bump the version? I've submitted this pull request for version bump (not sure if that's helpful) https://github.com/davodesign84/react-native-mixpanel/pull/259

**Comment by davodesign84** [comment]
Yes, I'll do it when I get in front of the PC. Yolo merge on mobile 😬😂

Hopefully mixpanel will be able to open up their beta soon.

**Comment by IevgenRagulin** [comment]
Yeah, would be awesome to have an implementation from mixpanel. Is there anything else that needs to be done to publish the change to npm or will github do this automatically?

**Comment by IevgenRagulin** [comment]
Nice, thanks @davodesign84 , I can see the new version in npm now

**Comment by IevgenRagulin** [comment]
@DipanshKhandelwal , the error is now gone, thank you for you PR. However, I keep getting the "autoshow" messages on ios. Do you remember if you had to do anything else to prevent "autoshow" on ios that's not mentioned in documentation? Do I need to remove this line from react native code perhaps? 

`Mixpanel.sharedInstanceWithToken(YOUR_PROJECT_TOKEN);`

**Comment by DipanshKhandelwal** [comment]
```
Mixpanel *mixpanel = [Mixpanel sharedInstanceWithToken:YOUR_MIXPANEL_TOKEN];
mixpanel.showNotificationOnActive = NO;
```

Did you initialise it in iOS code ? 
And set the value of `mixpanel.showNotificationOnActive` as `NO` ?

**Comment by IevgenRagulin** [comment]
Yeah, I did

**Comment by IevgenRagulin** [comment]
Tried importing Mixpanel like this:
#import "react-native-mixpanel/Mixpanel.h"

and like this:
import "Mixpanel/Mixpanel.h"

With same results

**Comment by DipanshKhandelwal** [comment]
No, I didn't do anything else apart from the `native initialization` and setting `mixpanel.showNotificationOnActive` as `NO`.
