### ISSUE TITLE
Android and documentation not in sync with changes introduced on ios side

### ISSUE THREAD

**Issue by anback** [davodesign84/react-native-mixpanel#26]
Sure this one was such a good idea ?

https://github.com/davodesign84/react-native-mixpanel/commit/630df996652eaec6255bc0bc7d1569f4d1b826ff

2 remarks:
1. Readme is not in sync with change
2. Android is not in sync with change,

I dont have time to look at it now, this was just a heads up, cheers

Might submit a PR when i get around to it

**Comment by davodesign84** [comment]
You are right, if you could help with a PR would be awesome!
