### ISSUE TITLE
Mixpanel.people.set

### ISSUE THREAD

**Issue by AashJ** [davodesign84/react-native-mixpanel#261]
What is the alternative for mixpanel.people.set as seen in the node.js documentation (https://developer.mixpanel.com/docs/nodejs)? 

My use case is I already have user profiles stored in a database, and am now adding in a mixpanel integration. I want to create user profiles if they don't already exist, but identify otherwise.

**Comment by eugenetraction** [comment]
If I'm not mistaken this is the syntax: 

`// Set People properties (warning: if no mixpanel profile has been assigned to the current user when this method is called, it will automatically create a new mixpanel profile and the user will no longer be anonymous in Mixpanel)
Mixpanel.set({"$email": "elvis@email.com"});

// Set People Properties Once (warning: if no mixpanel profile has been assigned to the current user when this method is called, it will automatically create a new mixpanel profile and the user will no longer be anonymous in Mixpanel)
Mixpanel.setOnce({"$email": "elvis@email.com", "Created": new Date().toISOString()});`
