### ISSUE TITLE
Not able to receive push notifications after upgrading Mixpanel Android SDK to 5.8.5 

### ISSUE THREAD

**Issue by kiitos-smasri** [davodesign84/react-native-mixpanel#265]
I did pull the upgrade but am not able to receive push notifications anymore

**Comment by kyleclegg** [comment]
I've tested both iOS and Android push notifications and they continue to work as expected prior to updating from 5.6.8 -> 5.8.5. Are you finding that you're not able to receive push notifications on iOS, Android, or both?

**Comment by kiitos-smasri** [comment]
I have tested Android only, I tested using two versions of the app, one with SDK 5.6.8 and the other with SDK 5.8.5
on the version that has SDK 5.8.5 -> push notification was not received at all

**Comment by kyleclegg** [comment]
Is this still an open issue? Looks like you found a working solution for https://github.com/davodesign84/react-native-mixpanel/issues/263 which appeared to be related.
