### ISSUE TITLE
.set method doesn't seem to set selected properties on the users.

### ISSUE THREAD

**Issue by mcnewbk** [davodesign84/react-native-mixpanel#29]
I am using the following lines of test code to track users of my app. It will fire and show the selected events for the user in Mixpanel, but it doesn't seem to set any of the people properties.

        Mixpanel.identify("8709196480");
        Mixpanel.set("$name", "Brandon McNew");
        Mixpanel.set('$phone', "870-919-6480");
        Mixpanel.set("$first_name", "Brandon");
        Mixpanel.set("$last_name", "McNew");
        Mixpanel.set("$email", "brandon@gatewayapps.com");
        Mixpanel.track("app_launched");

Is this a known issue or am I doing something incorrectly?

**Comment by mlevkovsky** [comment]
hey @mcnewbk did you get this working finally? For some reason I can't get any people properties to register either :/

**Comment by craigcoles** [comment]
Would be good to get a clarification on how you fixed this issue. I am experiencing the same issue. The`identify` works as expected, and so does the `trackWithProperties`, but I am not seeing any people data.

```
Mixpanel.identify( this.state.mixpanelId );

Mixpanel.set({
  "$first_name": this.state.user.first_name,
  "$last_name": this.state.user.last_name,
  "$email": this.state.user.email,
});

Mixpanel.trackWithProperties('signed up', { country: this.state.user.country });
```

**Comment by DmitryOlkhovoi** [comment]
The same here

**Comment by arnaudambro** [comment]
hi there, I'm in the same trouble, any idea ?
