### ISSUE TITLE
I get an error when building after following the install steps

### ISSUE THREAD

**Issue by dajomu** [davodesign84/react-native-mixpanel#3]
Hi, I'm pretty new to iOS and developing with cocoapod, so I apologise in advance if this is a rookie mistake.

I get a build error after following installation step 5 (Add libRNMixpanel.a to your project's Build Phases).

This is the the error:
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_Mixpanel", referenced from:
     objc-class-ref in libRNMixpanel.a(RNMixpanel.o)
```
(I get the same error when building for simulator, but with x86_64)

I'm pretty sure I'm doing step 5 correctly, but I am wondering if I'm not following step 6 correctly?
I go to the RNMixpanel.xcodeproj in my Project/Libraries folder, then edit the Header Search Paths like this -
```
$(inherited)
/Applications/Xcode.app/Contents/Developer/Toolchains/........
$(SRCROOT)/../../React
$(SRCROOT)/../../node_modules/react-native/React
$(SRCROOT)/../react-native/React
```
All recursive except inherited.

I also think it could be another issue with the installation of the cocoapod having to be for a specific version of ios, or not having copied some files across. Do you have any idea why I would be getting this problem?

Thanks

**Comment by davodesign84** [comment]
How does your Podfile look like?

**Comment by davodesign84** [comment]
How does you Podfile look like? Seems like an issue with the Pod itself, as RNMixpanel is loading and looking for Mixpanel, but can't find it.

**Comment by dajomu** [comment]
It just has the one line in it, that mixpanel themselves tell you to use [here](https://mixpanel.com/help/reference/ios) -
``` pod 'Mixpanel' ```

Since posting I've found a solution, on [stackoverflow](http://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods) -
Go to your target Build Settings -> Other linker flags -> double click . Add ```$(inherited)``` to a new line.

It was apparently because I was getting errors on ```pod install``` that looked like this -
```
[!] The `Corona [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. 
This can lead to problems with the CocoaPods installation
```

Hopefully this will help anyone else who comes across this issue.

**Comment by davodesign84** [comment]
Glad you could fix it, next time it would be best to use the command `pod init` first, which should create a Podfile looking like this

```
# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'YourProject' do

end

target 'YourProject' do

end
```

to which you can add `pod 'Mixpanel'` like so:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'YourProject' do
    pod 'Mixpanel'
end

target 'YourProject' do

end
```

**Comment by dajomu** [comment]
So does that mean that I don't have to use the xcworkspace that is generated? It would add it to the project itself?
Also, would I specify the Project just as 'YourProject', or would it be 'YourProject.xcodeproj'?

Thanks very much for the help.

**Comment by davodesign84** [comment]
Still need to use the workspace, but you just need to input the pod init command and it will take care of generating workspace and Podfile.

I would suggest to look at this https://cocoapods.org/

**Comment by dajomu** [comment]
Thanks again.

**Comment by davodesign84** [comment]
No worries! Let me know if that works better :)
