### ISSUE TITLE
Error installing library

### ISSUE THREAD

**Issue by SushilShrestha** [davodesign84/react-native-mixpanel#31]
I followed the instruction from documentation. have installed SDK and trying to link library to my project. And I get following error while building my project. 
```
/Users/.../node_modules/react-native-mixpanel/RNMixpanel/RNMixpanel.m:12:9: Module 'React' not found
```
header search path is as follows
```
$(inherited) => non-recursive
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include => recursive
$(SRCROOT)/../../React => recursive
$(SRCROOT)/../../node_modules/react-native/React => recursive
```
Am I missing something? I am using react-native 0.25.1

**Comment by davodesign84** [comment]
Hi @SushilShrestha , I removed React dependency.

Please try v.0.0.10, let me know if it works!

**Comment by SushilShrestha** [comment]
It's working now. Thanks @davodesign84.
