### ISSUE TITLE
setOnce is missing on Android

### ISSUE THREAD

**Issue by ms88privat** [davodesign84/react-native-mixpanel#38]
@kevinejohn thanks for integrating this library with Android. Could you please provide the setOnce method also? So we have future parity with the iOS Version.

Thanks!

**Comment by ms88privat** [comment]
Also I noticed that the API is different for set() between iOS and Android

**Comment by mikelambert** [comment]
I just noticed this today too, and have a change to fix this. I'll send a pull request now.

**Comment by mikelambert** [comment]
Looks like there is already a change committed in master for Mixpanel.set fix. So my change will just be for setOnce.
