### ISSUE TITLE
Linker command failed error when trying to build

### ISSUE THREAD

**Issue by guidsen** [davodesign84/react-native-mixpanel#41]
I keep getting this error when following your tutorial or using rnpm.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Mixpanel", referenced from:
      objc-class-ref in libRNMixpanel.a(RNMixpanel.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nevir** [comment]
You need to link the mixpanel into your application's binary

Follow the instructions at https://mixpanel.com/help/reference/ios or https://blog.mixpanel.com/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods/

**Comment by kevando** [comment]
Can you explain more what this means?

**Comment by kevando** [comment]
I am guessing you are referring to this missing libMixpanel.a right? But where do I get that?!

https://i.imgur.com/hzBWwc6.png

**Comment by zaynyatyi** [comment]
I'm getting same issue

**Comment by Frexuz** [comment]
For future people coming here. `react-native link` added libRNMixpanel-tvOS.a as well. I removed it from the Build Phase / Link binary with libraries, and the build was successful :) (I don't have a tvOS target, could be why?)
