### ISSUE TITLE
Mixpanel not found

### ISSUE THREAD

**Issue by JaysonMandani** [davodesign84/react-native-mixpanel#42]
library not found for -lMixpanel

GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Mixpanel"
LIBRARY_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/Mixpanel"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Mixpanel"
OTHER_LDFLAGS = $(inherited) -ObjC -l"Mixpanel" -l"icucore" -framework "Accelerate" -framework "CoreGraphics" -framework "CoreTelephony" -framework "Foundation" -framework "QuartzCore" -framework "SystemConfiguration" -framework "UIKit"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}/Pods

that is my generated pods.. I have Mixpanel directory on my project I already add the inherited paths on the links all the configuration was done.. But still the Mixpanel is missing. Please help thanks

**Comment by adambutler** [comment]
For anyone else who gets this issue open your `AppName.xcworkspace` file instead of your `AppName.xcodeproj` file in XCode
