### ISSUE TITLE
survey support

### ISSUE THREAD

**Issue by joshyg** [davodesign84/react-native-mixpanel#44]
Hi,

I am using react-native-mixpanel in an app I am working on and the features it is supporting are all working great.  I noticed you do not have a wrapper around:

 [mixpanel showSurveyWithID:CALL_QUALITY_SURVEY_ID]

Which is used to show a survey when the default behavior ( show the survey on load ) is not enabled.  Is there a reason this was not implemented?  If there isn't then I can go ahead and try adding the functionality and push it back to you, just wanted to see if there is some large difficulty you ran into that caused you to leave this out.

**Comment by davodesign84** [comment]
Hi there!

To be honest I haven't tried to expose it. please feel free to send a PR :)

**Comment by flavordaaave** [comment]
@joshyg have you successfully used surveys in your app? I just setup a survey on the mixpanel project and hoped that it will just popup sooner or later in my app but so far nothing happened. Shouldn't the default behavior (show survey on load) just work out of the box?

**Comment by aakashsigdel** [comment]
got this from the mixpanel site 
```
WE ARE DISCONTINUING MOBILE SURVEYS

We will be discontinuing the mobile surveys feature within our product, and it will be fully deprecated in March 2017.
```
So  I don't think supporting it would be a good idea. Closing the issue
