### ISSUE TITLE
Outdated version in npm?

### ISSUE THREAD

**Issue by steinnes** [davodesign84/react-native-mixpanel#48]
I just installed `react-native-mixpanel` via npm and the version that gets installed is `0.0.10`, but it seems to have a different version of the code than found here.  Most notably the `Mixpanel.set` method has a different signature than here on GitHub:

``` java
    @ReactMethod
    public void set(final String key, final String value) {
        mixpanel.getPeople().set(key, value);
    }
```

The generated package.json shows me that this is the file that it's fetching:
https://registry.npmjs.org/react-native-mixpanel/-/react-native-mixpanel-0.0.10.tgz, and I have fetched it manually untarred it and found the same offending code.  It seems to me that the version on npm is before this commit:
https://github.com/davodesign84/react-native-mixpanel/commit/06f0fd15a0f6cc072742ff47f71dd88bbffd8325

**Comment by nickw** [comment]
I also just got bit by this, the specific error Android throws is: 

`RNMixpanel.set got 1 arguments, expected 2`
