### ISSUE TITLE
Export is undefined

### ISSUE THREAD

**Issue by Zianwar** [davodesign84/react-native-mixpanel#50]
Hello!

I'm having an issue with the exports, I did : 

``` javascript
const Mixpanel = require('react-native-mixpanel');

console.info(Mixpanel); // undefined

Mixpanel.sharedInstanceWithToken(TOKEN); // cannot read property 'sharedInstanceWithToken' of undefined 
```

Using: 

```
"react": "15.2.1",
"react-native": "0.31.0",
"react-native-mixpanel": "0.0.10"
```

Even though I linked the library using `react-native link react-native-mixpanel`
which was linked successfully. 

![](https://cl.ly/hCvD/Screen%20Shot%202016-08-25%20at%2010.22.59%20AM.png)

**Comment by BennSandoval** [comment]
Add libRNMixpanel.a instead of libMixpanel.a

**Comment by AhsanWani** [comment]
+1

**Comment by karankrizz** [comment]
How did you solve this? I'm facing the same issue now. @Zianwar

**Comment by mu1ex** [comment]
Having this issue in android.

**Comment by mtpeoples** [comment]
Hello, I'm having the same issue with Mixpanel being undefined. I require it in my base component `App.js` after having followed the installation instructions for iOS and Android. I've also confirmed that @mu1ex and @BennSandoval suggestions have been implemented. I'm running out of ideas for what the problem could be, and would appreciate any insight that could be provided.

**Comment by rcorrie** [comment]
@mtpeoples I solved this issue by installing the mixpanel-ios via cocoapods.

**Comment by richao03** [comment]
I've installed 'Mixpanel' via cocoapods, and followed all the instructions above, but i am still getting Mixpanel is undefined, any updates here?

**Comment by nikodunk** [comment]
Console.log showed that it's actually Mixpanel.default.sharedInstanceWithToken(TOKEN) in my case.
