### ISSUE TITLE
RNMixpanel.trackCharge was called with 2 arguments but expects 1 

### ISSUE THREAD

**Issue by mlevkovsky** [davodesign84/react-native-mixpanel#51]
Hey there,

So as per the docs I tried calling track charge with a few props but ran into the error mentioned above.
This is my call:

`Mixpanel.trackCharge(this.props.variant.price,
        {'variant id':this.props.variant.id,'variant name':this.props.variant.title});`

I am on version 0.0.10 of the package. Any advice would be appreciated :)

**Comment by jamielob** [comment]
You need to call `Mixpanel.trackChargeWithProperties()` instead. 

Relevant: #71.

**Comment by jamielob** [comment]
FYI - the properties set here aren't visible in the Mixpanel UI, only in the raw data if you export it. This is a Mixpanel limitation.

**Comment by mlevkovsky** [comment]
Thank you :)
I figured it out that it was trackChargeWithProperties later, but forgot to close this issue 🙈
Closing it now
