### ISSUE TITLE
Issue when calling reset

### ISSUE THREAD

**Issue by bsiddiqui** [davodesign84/react-native-mixpanel#53]
This does not fire session end

``` js
mixpanel.track('session_end')
mixpanel.reset()
```

this does

``` js
mixpanel.reset()
```

Maybe the docs should be updated to point out that you should do something like this instead

``` js
Promise.resolve(mixpanel.track('session_end'))
.then(mixpanel.reset)
```

Happy to make a PR if you all think it makes sense.

**Comment by davodesign84** [comment]
Merged PR :)
