### ISSUE TITLE
RNMixpanel.set got 1 arguments, expected 2

### ISSUE THREAD

**Issue by jnrepo** [davodesign84/react-native-mixpanel#56]
![screenshot_2016-10-11-00-11-33](https://cloud.githubusercontent.com/assets/5111058/19261868/bfa597e8-8f48-11e6-9dcf-88f16740cd7a.png)

Not sure why this error happens on Android, everything for RNMixpanel.set seems to be correct :/

**Comment by dwilt** [comment]
Getting the exact same thing. And as @jnrepo mentioned, it's only happening on Android.

**Comment by mikelambert** [comment]
This was fixed in https://github.com/davodesign84/react-native-mixpanel/commit/06f0fd15a0f6cc072742ff47f71dd88bbffd8325 on May 20.

It's not in any released npm version though. So you'll have to make your packages.json point directly at github if you want to use it.

**Comment by dwilt** [comment]
Why is it not released in any npm versions!?!?!!

**Comment by jnrepo** [comment]
@mikelambert I seem to get this error when I build from that version:

```
node_modules/react-native-mixpanel/android/src/main/java/com/kevinejohn/RNMixpanel/RNMixpanelModule.java:168: error: cannot find symbol
            obj = RNMixpanelModule.reactToJSON(props);
                                               ^
  symbol:   variable props
  location: class RNMixpanelModule
1 error
```

:/

**Comment by mikelambert** [comment]
Please use github head, not a particular github version. This fix was submitted after the fix I mentioned above:
https://github.com/davodesign84/react-native-mixpanel/commit/6718c85ac2e659dab08f3affd6e51a9439b6e0f4

**Comment by jnrepo** [comment]
@mikelambert that worked and thank you!

**Comment by dwilt** [comment]
@jnrepo I wouldn't close this issue until this gets merged into the latest NPM version. Every one who downloads this repo and tries to use this method is going to run into this unless they see this issue thread.

**Comment by casenjo** [comment]
I ran into the same problem tonight and was wondering what was up with that. Thanks for leaving the issue open :)

**Comment by skylarmb** [comment]
Same issue! please release a new npm version soon

**Comment by davodesign84** [comment]
New version released
