### ISSUE TITLE
Build error : architecture problem

### ISSUE THREAD

**Issue by ghamaide** [davodesign84/react-native-mixpanel#6]
Hello, I get the following error after following your steps to integrate mix panel, have I done something wrong ?
![screen shot 2015-12-17 at 7 42 05 pm](https://cloud.githubusercontent.com/assets/6986811/11878493/7d80d2ac-a4f6-11e5-8fd4-15441696a9d8.png)

**Comment by davodesign84** [comment]
Most of the times this gets fixed by adding $(inherited) to the Other Linker Flags.
Check this SO answer: http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64

**Comment by ghamaide** [comment]
Yes, I tried it and it doesn't change a thing unfortunately. I made it work by integrating MixPanel with CocoaPods...

**Comment by davodesign84** [comment]
Closing.
