### ISSUE TITLE
library support

### ISSUE THREAD

**Issue by madhums** [davodesign84/react-native-mixpanel#61]
Hi @davodesign84, thank you for making this library! We have been using it in our organization to show in-app notifications. It works really well on iOS. We are having some troubles with Android where the in-app notification is not shown.

With all the new react-native [releases](https://github.com/facebook/react-native/releases), are you still planning on maintaining this library? Do you need help in maintaining? 

I see that @kevinejohn has worked on most of the android part. Are you still using this library and maintaining a fork of it @kevinejohn?

I am curious!

**Comment by aakashsigdel** [comment]
I don't think this library is maintained. Maybe someone is maintaining a fork of it? I submitted a PR half a month ago and got no response for it. Currently I've forked and added the features need to my fork.

Curious about a maintained mixpanel library for react-native.

**Comment by davodesign84** [comment]
Hi all, a friend pointed me toward this post. Unfortunately, I don't have time to maintain it anymore, but if anybody is willing to pick this up that would be super awesome.

**Comment by aakashsigdel** [comment]
I would love to, but I don't think I am very comfortable with Native android and ios development.

**Comment by davodesign84** [comment]
perhaps @madhums and @kevinejohn ? :)

**Comment by madhums** [comment]
I am also curious if mixpanel guys themselves would be interested! @davodesign84 do you think its a good idea to approach them? I my opinion it makes a lot of sense, that way we would also be able to get official help. Worth a try I would say. If you are ok, I can try contacting them. 

About the issue I was facing, I was able to get it to work on android too, had to follow some instructions according to mixpanel docs. I thought it would be a good idea to mention it in the Readme. I will send a PR later. 

Let me know what you think!

**Comment by skylarmb** [comment]
@madhums I talked to two Mixpanel onboarding engineers yesterday. They said they knew of people using Mixpanel in React Native but only in the sense of implementing it like it was a web app (javascript is javascript after all...), no native SDK. They were unaware of this native bridge so I sent them a link and they said they were going to check it out.

**Comment by madhums** [comment]
@skylarmb cool! Even I spoke to some support people but they said they didn't have any plans yet. Quite unfortunate. Did you hear anything from the engineers you spoke to?

**Comment by davodesign84** [comment]
Hey guys, still happy to add contributors to the package. It's currently difficult for me to follow this project 😭

**Comment by skylarmb** [comment]
@davodesign84 unfortunately the project I was using this for is being put on the back burner so I wont be working on it either.

**Comment by simaoneves** [comment]
Well, while someone doesn't come up to maintain the project, how about merge the PRs available? @davodesign84

**Comment by davodesign84** [comment]
PR Merged and npm version updated, still looking for collaborators!
