### ISSUE TITLE
Support for codeless tracking?

### ISSUE THREAD

**Issue by skylarmb** [davodesign84/react-native-mixpanel#63]
Is it even possible to take advantage of Mixpanel's codeless tracking feature (supported by the native iOS SDK) in a react native app? Currently if you navigate to the wysiwyg editor in Mixpanel you can get the app to render but it shows that there are no trackable elements on the screen. 

Did I set it up wrong or is this not a supported feature?

**Comment by Antonhansel** [comment]
any new information on this ?

**Comment by Gaboherrerobeaumont** [comment]
Hello! It would be a great feature to have available!

**Comment by 3gedge** [comment]
Hi, I'd like to know if it is possible now ? @davodesign84

**Comment by davodesign84** [comment]
I'm afraid I don't have time to look into it, but would gladly merge a PR!

**Comment by kyleclegg** [comment]
Closing because Mixpanel has subsetted codeless tracking.
https://mixpanel.com/blog/2019/03/05/codeless-analytics-problems/
