### ISSUE TITLE
where to add mixpanel token ? 

### ISSUE THREAD

**Issue by rajatgupta1993** [davodesign84/react-native-mixpanel#64]
I have followed the steps for manual installation and followed the following link [https://blog.mixpanel.com/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods/](url) 
In the 4th step of this link, we have to add this line 
`    [Mixpanel sharedInstanceWithToken:MIXPANEL_TOKEN];`  in launchOptions function of appDelegate.m. 

However, when i add this line it shows error : `use of undeclared identifier 'MIXPANEL_TOKEN'`.
and if I remove `    [Mixpanel sharedInstanceWithToken:MIXPANEL_TOKEN];` and the `#import "Mixpanel.h"` from appDelegate.m , the build succeeds. 
What should I do ?

**Comment by davodesign84** [comment]
You probably want to use Mixpanel.sharedInstanceWithToken(YOUR_PROJECT_TOKEN); in your Javascript files.
