### ISSUE TITLE
Android Build Failure after getDistinctID update: Missing Callback Class

### ISSUE THREAD

**Issue by dwilt** [davodesign84/react-native-mixpanel#67]
```
/Users/dwilt/Projects/GJS/gjs-app/node_modules/react-native-mixpanel/android/src/main/java/com/kevinejohn/RNMixpanel/RNMixpanelModule.java:263: error: cannot find symbol
    public void getDistinctId(Callback callback) {
                              ^
  symbol:   class Callback
  location: class RNMixpanelModule
1 error
:react-native-mixpanel:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```
After this [merge](https://github.com/davodesign84/react-native-mixpanel/pull/65), I'm getting this error on an Android build. I think we're missing a Class reference?

**Comment by yadavrohit** [comment]
I am also running into this issue. Is there a way to resolve this? Thanks

**Comment by shnooshnoo** [comment]
add "import com.facebook.react.bridge.Callback;"
to node_modules/react-native-mixpanel/android/src/main/java/com/kevinejohn/RNMixpanel/RNMixpanelModule.java

**Comment by dwilt** [comment]
thanks @shnooshnoo. We should get this integrated though - is there a PR
our for this?

**Comment by shnooshnoo** [comment]
@dwilt as I can see pull request #72 contains this

**Comment by dwilt** [comment]
Yep. I just approved. Who can merge these in?

**Comment by shnooshnoo** [comment]
Only those with write access to this repository can merge pull requests.

**Comment by zoontek** [comment]
No release planned for npm? The current version is broken.

**Comment by dwilt** [comment]
This plugin doesn't seem to be maintained very well. It's not getting PR's merged regularly and there are a lot of things missing. Sucks.

**Comment by zoontek** [comment]
Can @davodesign84 give the lead, maybe?
