### ISSUE TITLE
Duplicate method Error on RNMixpanel.m file

### ISSUE THREAD

**Issue by hetang-shah** [davodesign84/react-native-mixpanel#69]
Xcode is complaining about duplicate methods:
```
RCT_EXPORT_METHOD(addPushDeviceToken:(NSData *)deviceToken) {
    [mixpanel.people addPushDeviceToken:deviceToken];
}
```

and 

```
// addPushDeviceToken
RCT_EXPORT_METHOD(addPushDeviceToken:(NSString *)pushDeviceToken) {
  [mixpanel.people addPushDeviceToken:pushDeviceToken];
}
```

which one should we keep?

**Comment by ippa** [comment]
Got the same error.

**Comment by alanhoff** [comment]
Same error here

**Comment by bsiddiqui** [comment]
There's already a fix in master: https://github.com/davodesign84/react-native-mixpanel/commit/0511c0cc683c552eeeac125f70088f22afe6647a

I've just done it locally until a version bump.
