### ISSUE TITLE
React natives packager crashes with naming collision 

### ISSUE THREAD

**Issue by ippa** [davodesign84/react-native-mixpanel#70]
Seems to due to the Podfile dependency on `React`. 

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /project/node_modules/react-native/packager/package.json collides with /project/ios/Pods/React/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /project/node_modules/react-native/packager/package.json collides with /project/ios/Pods/React/packager/package.json

```

Also when doing `pod install` I get a warning:
`[!] React has been deprecated`

I've tested this on react-native 0.38 and 0.39.

This is my Podfile in react-native ios-directory:
```
use_frameworks!

target 'project' do
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel/react-native-mixpanel.podspec'
end
```

Simple removing the `s.dependency 'React'` from the Podfile creates other problems:
```
/project/node_modules/react-native-mixpanel/RNMixpanel/RNMixpanel.h:9:9: 'RCTBridgeModule.h' file not found

/project/node_modules/react-native-mixpanel/RNMixpanel/RNMixpanel.m:10:9: In file included from /project/node_modules/react-native-mixpanel/RNMixpanel/RNMixpanel.m:10:
```

And no matter what I add to react-native-mixpanels xcode Build Settings when it comes to Header/Library/Framework search paths I can't get `RNMixpanel.m` to find `RCTBridgeModule.h`... (even though it resides in `/project/node_modules/react-native/React/Base`)

**Comment by ippa** [comment]
There's a hackish way around this:

Putting this in `rn-cli.config.js` in the root of your project and start the packager with `react-native start --reset-cache`

```
var blacklist = require('react-native/packager/blacklist');

var config = {
  getBlacklistRE() {
    return blacklist([
      /ios\/Pods\/React\/.*/,
    ]);
  }
};

module.exports = config;
```

But then I get other runtime errors that also seem to be related to the outdated bundled React.
How are people solving this? ping @davodesign84

**Comment by jsappme** [comment]
+1

**Comment by davodesign84** [comment]
this should be solved with RN040 support, let me know if this isn't the case.
