### ISSUE TITLE
Error IOS: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by geecurve** [davodesign84/react-native-mixpanel#73]
Hi guys I'm getting this on a fresh react native project when i include this component. PS -> I first fixed the duplicate method issue manually from the master by replacing RNMixpanel.m 

Full error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Mixpanel", referenced from:
      objc-class-ref in libRNMixpanel.a(RNMixpanel.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Current react versions:
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-mixpanel": "0.0.11"

Hope you can help.

**Comment by zoontek** [comment]
@geecurve You forgot install the Mixpanel SDK. This package documentation suggest Cocoapods, but a simpler solution can be Carthage: https://github.com/Carthage/Carthage
Check the "Adding a framework" section in the README, add https://github.com/mixpanel/mixpanel-iphone :)

**Comment by kfiroo** [comment]
@zoontek any idea how I can do it without cocoapods?

**Comment by zoontek** [comment]
@kfiroo 

```
brew update && brew install carthage
cd ./ios && echo "github "mixpanel/mixpanel-iphone" ~> 3.0.8" > Cartfile
carthage update --platform iOS
```

and after that: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Comment by nihgwu** [comment]
@davodesign84 this kind of issues #41 #6 #3  should not be closed so arbitrary, there are still a lot of people who don't won't to use the CocoaPods, while the official doc on that missed something and leads us here. I figured out how to fix it after finding this finally http://stackoverflow.com/questions/32363208/symbols-not-found-for-architecture-x86-64-objc-class-mixpanel-referenced

The key point is that simply dragging the **Mixpanel** folder to your project is not enough, the source files of MixPanel are still not included in **Build Phases/Complie Sources**, you need to set the options too
![image](https://cloud.githubusercontent.com/assets/2595058/23354287/6cb92c6c-fd0b-11e6-94e1-19d5a3ca350f.png)
