### ISSUE TITLE
RNMixpanel was called with 2 arguments, but expects 1

### ISSUE THREAD

**Issue by jaimecorrea** [davodesign84/react-native-mixpanel#75]
![captura de pantalla 2016-12-22 a las 8 38 14 a m](https://cloud.githubusercontent.com/assets/18601530/21427355/204f4172-c822-11e6-8fb7-4b8151b69759.png)

**Comment by jamielob** [comment]
@jaimecorrea Are you trying to track with properties, passing the properties object as the second argument?  If so, you'll need to use `trackWithProperties` instead of `track`.
