### ISSUE TITLE
RN 40 support?

### ISSUE THREAD

**Issue by jeveloper** [davodesign84/react-native-mixpanel#78]
Hi there

There are breaking changes 

https://github.com/facebook/react-native/releases/tag/v0.40.0

Curious if any plans to alter this code or if there is a better mixpanel lib for RN 

thanks

**Comment by julienroussel** [comment]
Seems to be a pull request pending here #77

**Comment by aubreywahl** [comment]
I'm pretty sure that this library is not actively maintained

https://github.com/davodesign84/react-native-mixpanel/issues/61#issuecomment-256614504

**Comment by davodesign84** [comment]
Merged :)

**Comment by jeveloper** [comment]
Thanks @davodesign84 that's awesome
