### ISSUE TITLE
Does this work on Android too?

### ISSUE THREAD

**Issue by jihopark** [davodesign84/react-native-mixpanel#8]

**Comment by davodesign84** [comment]
Unfortunately it doesn't, but I'll happily merge a pull request if somebody can help :)

**Comment by kevinejohn** [comment]
I started working on that. Just need to test it

https://github.com/kevinejohn/react-native-mixpanel/tree/android

**Comment by ghamaide** [comment]
@kevinejohn any plans on opening a PR soon ?

**Comment by davodesign84** [comment]
Looking forward the PR :)

On 17 February 2016 at 11:02, ghamaide <notifications@github.com> wrote:

> @kevinejohn <https://github.com/kevinejohn> any plans on opening a PR
> soon ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davodesign84/react-native-mixpanel/issues/8#issuecomment-185155628>
> .
>



-- 
Davide Scalzo |* Product Director *
*Phone*: 07719 311697

<https://yplanapp.com/>

**Comment by kevinejohn** [comment]
I've been using it in my production app without any problems so I think its ready.

https://github.com/davodesign84/react-native-mixpanel/pull/13

**Comment by davodesign84** [comment]
Merged :)
