### ISSUE TITLE
Redux logging

### ISSUE THREAD

**Issue by Amurmurmur** [davodesign84/react-native-mixpanel#81]
Is it possible to just send all the redux actions (or most of them aka filter specific actions not to be sent) to mixpanel with this package?

If yes, how to set it up as a middleware?
Is it possible to set meta data in the action body to track that way as well?
Yours sincerely?

Thanks a lot in advance !!

**Comment by jaywalklabs** [comment]
we're doing exactly this with https://github.com/danscan/rn-redux-mixpanel and not react-native-mixpanel

**Comment by Amurmurmur** [comment]
@jaywalklabs that escalated quickly, thats legit, exactly what I was looking for!! Thank you so much!!
