### ISSUE TITLE
Need Collaborators

### ISSUE THREAD

**Issue by davodesign84** [davodesign84/react-native-mixpanel#82]
Hi all,

as you might have noticed I've been struggling to maintain this library. Apologies for the inconvenience caused, I merged the PRs and updated the npm version.

If anyone would like to step up and help out with testing pull requests it would be an immense help to me and the community :)

Let me know if you are interested!

Thanks again for your patience.

**Comment by aakashsigdel** [comment]
@davodesign84  I would like to help out if that is okay with you.

**Comment by davodesign84** [comment]
Thanks @aakashsigdel I made you a collaborator :)

Would be good to have somebody else helping out on the android side perhaps?

**Comment by aakashsigdel** [comment]
Yes, that would be great. I will try to find someone as well.

**Comment by davodesign84** [comment]
Awesome, thanks for helping :)

**Comment by StevePotter** [comment]
@davodesign84  I'm adept in Java and objC.  I'd be happy to help with the Android or iOS side.  In fact I was just inside your Android module code.  Put me down as a contributor and feel free to assign me work

**Comment by StevePotter** [comment]
@davodesign84  I'm adept in Java and objC.  I'd be happy to help with the Android or iOS side.  In fact I was just inside your Android module code.  Put me down as a contributor and feel free to assign me work.

Also have you considered reaching out to mixpanel themselves?  You have thousands of downloads and it'll only grow as RN matures.

**Comment by aakashsigdel** [comment]
@StevePotter I think somebody here did that with no luck.

**Comment by davodesign84** [comment]
Yeah it was tried but the team didn't show much interest. Might be worth retrying though. I'll see if I can reach somebody there.

Thanks so much guys for helping!

**Comment by StevePotter** [comment]
@davodesign84 we are a heavy mixpanel user and I'll drop a line with them and see if anything comes back
