### ISSUE TITLE
'React/RCTBridgeModule.h' file not found.

### ISSUE THREAD

**Issue by vivekdhar** [davodesign84/react-native-mixpanel#95]
Hello!
After running through the installation process when I attempt to build my project, I see the following error:
![screen shot 2017-04-21 at 1 39 59 pm](https://cloud.githubusercontent.com/assets/1569253/25295443/59af7c8c-2698-11e7-84b7-0e22e59b36fe.png)

- I've run npm install
- I've run react-native link
- And I've also installed the Mixpanel iOS SDK using Cocoapods
... all without any errors.

Has anybody seen this before or run into something like this?
Thanks! 

Edit:
`react-native@0.37.0`
`react-native-mixpanel@0.0.15`

**Comment by vivekdhar** [comment]
Upgraded to react-native .40.

**Comment by seque1990** [comment]
Is there any other way around without updating react native to version `0.40.0`?

**Comment by stereodenis** [comment]
@seque1990 remove "React/" from the path
